### ISSUE TITLE
How to get Earlier Crawls 

### ISSUE THREAD

**Issue by shikunyu8** [applicaai/CCpdf#3]
Thanks for sharing the processed pdfs in May 2022 crawl.

Can you share the pipeline that you used to create the ccpdf.tsv.xz? I'd like to get data from earlier crawls.

**Comment by tballison** [comment]
At the risk of self promotion, maybe check out: https://github.com/tballison/commoncrawl-fetcher-lite 

The work behind ccpdf and the paper are awesome!  Many thanks to the authors!

**Comment by MichalTurski** [comment]
Unfortunately, due to company data policy, we can't share any more data/code.  However there is open [thread](https://github.com/applicaai/CCpdf/issues/2) with open discussion on reproduction of the pipeline.
